version: 2.1

parameters:
  repo_name:
    type: string
    default: "app"

orbs:
  python: circleci/python@3.0.0

jobs:
  clone_repo:
    docker:
      - image: cimg/base:2025.02
    steps:
      - run:
          name: Clone repo
          command: |
            git clone https://github.com/CircleCI-Public/sample-python-cfd.git << pipeline.parameters.repo_name >>
            mkdir -p ~/workspace
            mv << pipeline.parameters.repo_name >> ~/workspace/
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - << pipeline.parameters.repo_name >>

  build_and_test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Check repo
          command: |
            cd ~/workspace/<< pipeline.parameters.repo_name >>
            ls -la
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/workspace/<< pipeline.parameters.repo_name >>/
      - run:
          command: |
            pip uninstall connexion
            pip install connexion==2.14.2
            pytest --version
            pytest ~/workspace/<< pipeline.parameters.repo_name >>
          name: Test
      - store_test_results:
          path: ~/workspace/<< pipeline.parameters.repo_name >>/test-results

workflows:
  orb_build_app:
    jobs:
      - clone_repo
      - build_and_test:
          requires:
            - clone_repo
