version: 2.1

parameters:
  repo_name:
    type: string
    default: "app"

orbs:
  python: circleci/python@3.0.0

jobs:
  clone_repo:
    docker:
      - image: cimg/base:2025.02
    steps:
      - run:
          name: Clone repo
          command: |
            git clone https://github.com/CircleCI-Public/sample-python-cfd.git << pipeline.parameters.repo_name >>
            mkdir -p ~/workspace
            mv << pipeline.parameters.repo_name >> ~/workspace/
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - << pipeline.parameters.repo_name >>

  build_and_test:
    docker:
      - image: cimg/python:3.10.5
    parameters:
      test_result_folder:
        type: string
        default: "test-report"
    steps:
      - attach_workspace:
          at: ~/workspace
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/workspace/<< pipeline.parameters.repo_name >>/
      - run:
          name: Run Test (fix package) and create test-report directory
          command: |
            mkdir ~/<< parameters.test_result_folder >>
            pip uninstall connexion -y
            pip install connexion==2.14.2
            pytest ~/workspace/<< pipeline.parameters.repo_name >> --junitxml=~/<< parameters.test_result_folder >>/results.xml
      - store_test_results:
          path: ~/<< parameters.test_result_folder >>

workflows:
  orb_build_app:
    jobs:
      - clone_repo
      - build_and_test:
          requires:
            - clone_repo
